permissions:
  id-token: write
  contents: read

name: Django CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      
      - name: Run linting
        run: ruff check .

      - name: Run tests with coverage
        run: |
          coverage run manage.py test
          coverage report --fail-under=80

      - name: Debug OIDC
        uses: github/actions-oidc-debugger@main

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::493667572198:role/github-django-docker-ecr
          aws-region: ap-south-1

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push Docker image
        run: |
          docker build -t django-docker .
          docker tag django-docker:latest 493667572198.dkr.ecr.ap-south-1.amazonaws.com/django-docker:${{ github.sha }}
          docker push 493667572198.dkr.ecr.ap-south-1.amazonaws.com/django-docker:${{ github.sha }}